In [5]:
import torch

In [13]:
device = "cuda"
# Cargar los estados de los modelos
estado_fase_0 = torch.load('Fase_0.pth')
estado_fase_1 = torch.load('Fase_1.pth')
total = torch.load('Total.pth')

In [7]:
from pprint import pprint
pprint([(indice ,torch.norm(row) ) for indice ,row in enumerate(total["linear_relu_stack.4.weight"])])


[(0, tensor(1.6721, device='cuda:0')),
 (1, tensor(1.6825, device='cuda:0')),
 (2, tensor(1.9504, device='cuda:0')),
 (3, tensor(1.8717, device='cuda:0')),
 (4, tensor(1.8533, device='cuda:0')),
 (5, tensor(2.0709, device='cuda:0')),
 (6, tensor(1.7862, device='cuda:0')),
 (7, tensor(1.9132, device='cuda:0')),
 (8, tensor(1.8989, device='cuda:0')),
 (9, tensor(1.9440, device='cuda:0'))]


In [8]:

pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_1["linear_relu_stack.4.weight"])])

pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_0["linear_relu_stack.4.weight"])])


[(0, tensor(1.0885, device='cuda:0')),
 (1, tensor(1.1788, device='cuda:0')),
 (2, tensor(1.0828, device='cuda:0')),
 (3, tensor(1.0519, device='cuda:0')),
 (4, tensor(1.0918, device='cuda:0')),
 (5, tensor(1.1024, device='cuda:0')),
 (6, tensor(1.1892, device='cuda:0')),
 (7, tensor(1.2835, device='cuda:0')),
 (8, tensor(1.0450, device='cuda:0')),
 (9, tensor(1.1354, device='cuda:0'))]
[(0, tensor(1.1791, device='cuda:0')),
 (1, tensor(1.2430, device='cuda:0')),
 (2, tensor(1.1531, device='cuda:0')),
 (3, tensor(1.1304, device='cuda:0')),
 (4, tensor(1.2186, device='cuda:0')),
 (5, tensor(0.6317, device='cuda:0')),
 (6, tensor(0.6541, device='cuda:0')),
 (7, tensor(0.6602, device='cuda:0')),
 (8, tensor(0.6607, device='cuda:0')),
 (9, tensor(0.6392, device='cuda:0'))]


In [14]:
print(total["linear_relu_stack.4.bias"])
print(estado_fase_0["linear_relu_stack.4.bias"])
print(estado_fase_1["linear_relu_stack.4.bias"])


tensor([-0.1553,  0.1768,  0.0250, -0.1029, -0.0096,  0.2021, -0.0447,  0.0962,
        -0.1736, -0.0115], device='cuda:0')
tensor([ 0.0024,  0.2560,  0.0607,  0.0721,  0.2004, -0.1442, -0.1317, -0.0835,
        -0.0938, -0.1330], device='cuda:0')
tensor([-0.0682,  0.1950, -0.0023,  0.0098,  0.1108,  0.0057, -0.0663,  0.0773,
        -0.1807, -0.0756], device='cuda:0')


In [15]:
print(torch.norm(total["linear_relu_stack.4.bias"]))
print(torch.norm(estado_fase_0["linear_relu_stack.4.bias"]))
print(torch.norm(estado_fase_1["linear_relu_stack.4.bias"]))

tensor(0.3861, device='cuda:0')
tensor(0.4315, device='cuda:0')
tensor(0.3222, device='cuda:0')


### Model stack

In [5]:
import torch
from pprint import pprint

In [21]:
estado_fase_0_stack = torch.load('Fase_0_stack.pth')
estado_fase_1_stack = torch.load('Fase_1_stack.pth')
total = torch.load('Total.pth')

In [16]:

pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_1_stack["linear_relu_stack.4.weight"])])

pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_0_stack["linear_relu_stack.4.weight"])])


[(0, tensor(1.0750, device='cuda:0')),
 (1, tensor(1.1154, device='cuda:0')),
 (2, tensor(0.9266, device='cuda:0')),
 (3, tensor(0.9677, device='cuda:0')),
 (4, tensor(1.0389, device='cuda:0')),
 (5, tensor(0.9462, device='cuda:0')),
 (6, tensor(1.0555, device='cuda:0')),
 (7, tensor(1.0802, device='cuda:0')),
 (8, tensor(0.8017, device='cuda:0')),
 (9, tensor(0.9035, device='cuda:0'))]
[(0, tensor(1.0778, device='cuda:0')),
 (1, tensor(1.1147, device='cuda:0')),
 (2, tensor(0.9247, device='cuda:0')),
 (3, tensor(0.9733, device='cuda:0')),
 (4, tensor(1.0547, device='cuda:0'))]


In [11]:
pprint([(indice ,torch.norm(row) ) for indice ,row in enumerate(total["linear_relu_stack.4.weight"])])


[(0, tensor(1.6721, device='cuda:0')),
 (1, tensor(1.6825, device='cuda:0')),
 (2, tensor(1.9504, device='cuda:0')),
 (3, tensor(1.8717, device='cuda:0')),
 (4, tensor(1.8533, device='cuda:0')),
 (5, tensor(2.0709, device='cuda:0')),
 (6, tensor(1.7862, device='cuda:0')),
 (7, tensor(1.9132, device='cuda:0')),
 (8, tensor(1.8989, device='cuda:0')),
 (9, tensor(1.9440, device='cuda:0'))]


### Comparativa

In [22]:
pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_0_stack["linear_relu_stack.4.weight"])])
pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_0["linear_relu_stack.4.weight"])])

[(0, tensor(1.0778, device='cuda:0')),
 (1, tensor(1.1147, device='cuda:0')),
 (2, tensor(0.9247, device='cuda:0')),
 (3, tensor(0.9733, device='cuda:0')),
 (4, tensor(1.0547, device='cuda:0'))]
[(0, tensor(1.1791, device='cuda:0')),
 (1, tensor(1.2430, device='cuda:0')),
 (2, tensor(1.1531, device='cuda:0')),
 (3, tensor(1.1304, device='cuda:0')),
 (4, tensor(1.2186, device='cuda:0')),
 (5, tensor(0.6317, device='cuda:0')),
 (6, tensor(0.6541, device='cuda:0')),
 (7, tensor(0.6602, device='cuda:0')),
 (8, tensor(0.6607, device='cuda:0')),
 (9, tensor(0.6392, device='cuda:0'))]


In [18]:
pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_1_stack["linear_relu_stack.4.weight"])])
pprint([ (indice,torch.norm(row)) for indice,row in enumerate(estado_fase_1["linear_relu_stack.4.weight"])])

[(0, tensor(1.0750, device='cuda:0')),
 (1, tensor(1.1154, device='cuda:0')),
 (2, tensor(0.9266, device='cuda:0')),
 (3, tensor(0.9677, device='cuda:0')),
 (4, tensor(1.0389, device='cuda:0')),
 (5, tensor(0.9462, device='cuda:0')),
 (6, tensor(1.0555, device='cuda:0')),
 (7, tensor(1.0802, device='cuda:0')),
 (8, tensor(0.8017, device='cuda:0')),
 (9, tensor(0.9035, device='cuda:0'))]
[(0, tensor(1.0885, device='cuda:0')),
 (1, tensor(1.1788, device='cuda:0')),
 (2, tensor(1.0828, device='cuda:0')),
 (3, tensor(1.0519, device='cuda:0')),
 (4, tensor(1.0918, device='cuda:0')),
 (5, tensor(1.1024, device='cuda:0')),
 (6, tensor(1.1892, device='cuda:0')),
 (7, tensor(1.2835, device='cuda:0')),
 (8, tensor(1.0450, device='cuda:0')),
 (9, tensor(1.1354, device='cuda:0'))]


In [19]:
pprint([(indice ,torch.norm(row) ) for indice ,row in enumerate(total["linear_relu_stack.4.weight"])])


[(0, tensor(1.6721, device='cuda:0')),
 (1, tensor(1.6825, device='cuda:0')),
 (2, tensor(1.9504, device='cuda:0')),
 (3, tensor(1.8717, device='cuda:0')),
 (4, tensor(1.8533, device='cuda:0')),
 (5, tensor(2.0709, device='cuda:0')),
 (6, tensor(1.7862, device='cuda:0')),
 (7, tensor(1.9132, device='cuda:0')),
 (8, tensor(1.8989, device='cuda:0')),
 (9, tensor(1.9440, device='cuda:0'))]
